extends RefCounted
class_name CombatRanges

const AGGRO_RADIUS: float = 225.0
const LEASH_DISTANCE: float = 1000.0
const PATROL_RADIUS: float = 225.0

const CHARACTER_MODEL_REFERENCE_SCALE: float = 0.2
const MELEE_ATTACK_RANGE_MODEL_PX: float = 400.0
const MELEE_ATTACK_RANGE: float = MELEE_ATTACK_RANGE_MODEL_PX * CHARACTER_MODEL_REFERENCE_SCALE
const RANGED_ATTACK_RANGE_BASE: float = 330.0
const RANGED_CAST_RANGE_BASE: float = RANGED_ATTACK_RANGE_BASE * 1.2
